### ISSUE TITLE
一个小问题，如何设置多用户。debian 7

### ISSUE THREAD

**Issue by johhnyocean** [teddysun/shadowsocks_install#13]
感谢大佬~一个命令就能部署好SS服务器造福小白，但是想给朋友偶尔用一下，自己的又部署在路由，所以想再开1个用户，希望得到指点，非常感谢，由于是用的您的Shadowsocks libev版，应该是想知道多进程的方法

**Comment by teddysun** [comment]
referring URL：
https://shadowsocks.be/7.html

**Comment by johhnyocean** [comment]
那么VPS上只有一个IP地址是不是全部source 到1个IP即可？
