### ISSUE TITLE
我使用shadowsocks-all.sh脚本安装go版本的ss报错了

### ISSUE THREAD

**Issue by codesboy** [teddysun/shadowsocks_install#19]
如图
![13](https://cloud.githubusercontent.com/assets/9047357/23006288/dfe188de-f43b-11e6-9051-42719f51974d.png)

**Comment by teddysun** [comment]
系统在安装 gzip 的时候，内存不足导致安装失败。
这 VPS 是内存有多小？

**Comment by codesboy** [comment]
128M的？128的只适合安装Python版的？

**Comment by worldfar2016** [comment]
python 版  内存消耗大，建议你128 跑 libv的版本 可以。
