### ISSUE TITLE
请问python一键安装包如何开启 onetime authentication

### ISSUE THREAD

**Issue by kang000feng** [teddysun/shadowsocks_install#2]
博主你好，请问您的python一键安装包如何开启 onetime authentication，您的安装包为什么不默认开启OTA呢？是出于什么考虑的？谢谢。

**Comment by teddysun** [comment]
Python 原版作者因为你懂的原因而停止更新。最新版本则停留在 2015 年 8 月的 2.8.2
所以是没有 onetime authentication 的。

**Comment by zzhhbyt1** [comment]
新版脚本使用的新python服务端可以开启了，安装新版服务端后在配置文件里加上`"auth": true`即可。
