### ISSUE TITLE
./shadowsocks-libev-debian.sh: line 331: ./configure: No such file or directory

### ISSUE THREAD

**Issue by fqx** [teddysun/shadowsocks_install#20]
There is only configure.ac and need to process this file with autoconf to produce a configure script.

**Comment by teddysun** [comment]
See download link:
https://github.com/shadowsocks/shadowsocks-libev/releases/download/v3.0.3/shadowsocks-libev-3.0.3.tar.gz

There is have a configure script in this release file.

So, please download latest script and run it.
