### ISSUE TITLE
shadowsocks-libev-debain自动安装脚本会出错

### ISSUE THREAD

**Issue by Jexbat** [teddysun/shadowsocks_install#21]
libsodium会默认安装在`/usr/local/lib/`目录下，但是shadowsocks-libev链接的时候会去`/usr/lib`目录去找，导致链接出错，无法完成编译，用`ln -s /usr/local/lib/libsodium.la /usr/lib/libsodium.la`可解决

**Comment by teddysun** [comment]
Fixed.
Use option ./configure --prefix=/usr when compiling libsodium.
