### ISSUE TITLE
多用户配置没用?

### ISSUE THREAD

**Issue by Lavinci** [teddysun/shadowsocks_install#29]
pyhton的安装版本,很高兴在vps上安装成功了
可是配置多用户只有第一个能用(都能连接,但只有第一个能正确访问互联网,也配置过iptables了)
{
    "server":"0.0.0.0",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
    "8080":"password",
    "8081":"password",
    "8082":"password"
    },
    "timeout":300,
    "method":"aes-128-gcm",
    "fast_open":true
}
在自己家里的fedora上安装是可以多用户的
实在找不到原因,只好找您问问了
能给点建议吗?谢谢

**Comment by zzl81cn** [comment]
重启：/etc/init.d/shadowsocks restart

**Comment by Lavinci** [comment]
thx
