### ISSUE TITLE
Shadowsocks libev 多IP出口

### ISSUE THREAD

**Issue by JasonVeryGood** [teddysun/shadowsocks_install#3]
秋水大大。Shadowsocks libev版设置多IP出口。如果有200来个IP可以正常跑起来？

**Comment by teddysun** [comment]
取决于机器配置。
建议使用 ShadowsocksR，目前已经默认支持多 IP。

**Comment by JasonVeryGood** [comment]
@teddysun SSR 需要绑定IP？比如有200个外网IP。不用绑定入口IP的？开个多端口和用户就行了？

**Comment by teddysun** [comment]
@JasonVeryGood 无需绑定。从哪个 IP 连接就是哪个 IP。开多个端口即可。

**Comment by allencourtney937** [comment]
@teddysun 你好，你能详细说一下如何一个vps多个ip，一个ip对应一个ssr账号的设置方法吗？ 能写篇简单的教程放到你的网站吗？ 谢谢
