### ISSUE TITLE
ssr not working in Ubuntu 14.04

### ISSUE THREAD

**Issue by Murphy0571** [teddysun/shadowsocks_install#31]
Hi Teddy,

First of all, many thanks for your great script of installing ssr.

However, after installing, it seems not working in my Ubuntu 14.04 environment. Here's the outcome of running "service shadowsocks start":
-----------------------------------log begin------------------------------------------------
murphy@murphy-ThinkPad-X260:~$ sudo service shadowsocks start
IPv6 support
2017-08-15 16:49:13 INFO     util.py:85 loading libsodium from libsodium.so.18
2017-08-15 16:49:13 INFO     shell.py:72 ShadowsocksR 3.4.0 2017-07-27
started
Starting ShadowsocksR success
murphy@murphy-ThinkPad-X260:~$ ping www.baidu.com
PING www.a.shifen.com (115.239.211.112) 56(84) bytes of data.
64 bytes from 115.239.211.112: icmp_seq=1 ttl=56 time=3.32 ms
64 bytes from 115.239.211.112: icmp_seq=2 ttl=56 time=3.49 ms
64 bytes from 115.239.211.112: icmp_seq=3 ttl=56 time=4.73 ms
^C
--- www.a.shifen.com ping statistics ---
4 packets transmitted, 3 received, 25% packet loss, time 3005ms
rtt min/avg/max/mdev = 3.329/3.854/4.738/0.630 ms
murphy@murphy-ThinkPad-X260:~$ ping www.google.com
PING www.google.com (243.185.187.39) 56(84) bytes of data.
^C
--- www.google.com ping statistics ---
20 packets transmitted, 0 received, 100% packet loss, time 19000ms
-----------------------------------log end------------------------------------------------

I'm pretty sure the ssr server side is working because in my Windows environment everything is working perfectly using the same server.

Any comments?

Many thanks!
Murphy

**Comment by dy2k** [comment]
the required dependency - https://github.com/shadowsocks/shadowsocks

"Removed according to regulations."
