### ISSUE TITLE
ssr blocked by isp

### ISSUE THREAD

**Issue by tiantianlecheng** [teddysun/shadowsocks_install#36]
SSR setting is ok, and can work well in the office network, cannot work at home, probably blocked by ISP, any suggestion? thanks a lot.

**Comment by msn1983aa** [comment]
正常啦，19大要开了，我的搬瓦工昨天开始就被墙了，正在给搬瓦工发工单。
你是搬瓦工还是哪家的梯子？

2017-10-10 10:52 GMT+08:00 tiantianlecheng <notifications@github.com>:

**Comment by tiantianlecheng** [comment]
I don't expect the ISP for my home can block my ssr so effectively. in office, no problem.

**Comment by msn1983aa** [comment]
现在的状况是ping没问题，但是翻墙不行，估计是ssr被特征封锁了，ssr已被攻破

2017-10-10 17:23 GMT+08:00 tiantianlecheng <notifications@github.com>:

**Comment by climbthewall** [comment]
Is it still the same? My ISP seems okay with the SSR.
