### ISSUE TITLE
在AWS上无法重启

### ISSUE THREAD

**Issue by kresnikwang** [teddysun/shadowsocks_install#37]
我配置了一个centos 7版本的ECS在aws上面，安装配置没有问题。
但是配置完之后，用sudo命令重启ss服务，重启不起来，一直是stopped的状态。

感谢，
Kris

**Comment by tefiszx** [comment]
sudo 命令能重启服务？怎么着也应该用systemctl 命令吧。一键安装包应该有开启启动脚本吧，安装无错的话，只要写配置文件就可以了，其他不用管了。
