### ISSUE TITLE
centos6.5上安装haproxy时出现line 194: /etc/init.d/haproxy: No such file or directory

### ISSUE THREAD

**Issue by yanlzhl** [teddysun/shadowsocks_install#39]
安装完成之后，系统提示：
Congratulations, haproxy install completed.
Your haproxy Server IP: your_haproxy_server_ip
Your haproxy Server port: your_haproxy_server_port
Your Input Shadowsocks IP: your_shadowsocks_server_ip

Welcome to visit:https://shadowsocks.be/10.html
Enjoy it.
也就是安装成功，
但是，在 /etc/init.d/目录下，没有haproxy文件，希望得到你的帮助，非常感谢你的开源奉献精神~

**Comment by teddysun** [comment]
执行以下命令，看看有无输出信息，若有，则安装正常，若没有，则反之。
`rpm -qa | grep haproxy`

**Comment by yanlzhl** [comment]
执行了你的这条命令，输出了：haproxy-1.5.18-6.el7.x86_64
==========================================================
安装过程提示信息：
Running transaction
  Installing : haproxy-1.5.18-6.el7.x86_64                                  1/1 
  Verifying  : haproxy-1.5.18-6.el7.x86_64                                  1/1 

Installed:
  haproxy.x86_64 0:1.5.18-6.el7                                                 

Complete!
haproxy install successed.
Config haproxy start...
Config haproxy completed...
error reading information on service haproxy: No such file or directory
Note: Forwarding request to 'systemctl enable haproxy.service'.
Created symlink from /etc/systemd/system/multi-user.target.wants/haproxy.service to /usr/lib/systemd/system/haproxy.service.
./haproxy.sh: line 194: /etc/init.d/haproxy: No such file or directory
haproxy start failure...
./haproxy.sh: line 208: /etc/init.d/haproxy: No such file or directory
......  
Congratulations, haproxy install completed.
Your haproxy Server IP:  xxx
Your haproxy Server port:  xxx
Your Input Shadowsocks IP:  xxx
Welcome to visit: https://shadowsocks.be/10.html
Enjoy it.

========================
然后执行/etc/init.d/haproxy status自然没用，疑惑，希望耽误你几分钟时间看看，感激。

**Comment by yanlzhl** [comment]
似乎成了，再上一步骤的基础上执行：systemctl enable haproxy.service再执行systemctl start haproxy.service，再执行ps -ef |grep haproxy可以看到haproxy再运行了。
===================================
/etc/init.d/haproxy status始终没有用

**Comment by teddysun** [comment]
感谢反馈！
脚本比较旧了，那是以前的写法。
更新了。
