### ISSUE TITLE
为大神点赞

### ISSUE THREAD

**Issue by wulol** [teddysun/shadowsocks_install#42]
推上关注了，用你脚本解决太多菜鸟问题了，引路者。没碰到过错，现在也懂点linux 了，学了点编译，小问题就谷歌了，没毛病。感谢。我也注册了git 账号，居然能保存，谢谢！

**Comment by zhanchengqian** [comment]
@wulol 请问你用的VPS是什么？

**Comment by wulol** [comment]
VULTR低端产品呢。

2017-11-08 5:19 GMT+08:00 Zhancheng Qian <notifications@github.com>:
