### ISSUE TITLE
请问在哪里查看运行的日志

### ISSUE THREAD

**Issue by leewi9** [teddysun/shadowsocks_install#46]
RT

**Comment by leewi9** [comment]
为什么在香港阿里云部署之后，其它网站都能打开，就是youtube打不开

**Comment by yanweijia** [comment]
find / -name "shadowsocks.log"
vim /var/log/shadowsocks.log

**Comment by cld378632668** [comment]
或者看shadowsocks/shadowsocks 项目中开启管理模式(不用此项目搭建),命令如下
① Ubuntu
sudo apt install python-pip
pip install git+https://github.com/shadowsocks/shadowsocks.git@master
② CentOS
sudo yum install python-setuptools && easy_install pip
pip install git+https://github.com/shadowsocks/shadowsocks.git@master
同样配置好/etc/shadowsocks.json
ssserver --manager-address 0.0.0.0:6001 -c /etc/shadowsocks.json -d restart
这个时候就可以看本地6001端口的信息了



请问做以上操作有什么作用？  跟看日志有什么不一样？
