### ISSUE TITLE
建议：把SSR项目替换为SSRR

### ISSUE THREAD

**Issue by Mr-Jos** [teddysun/shadowsocks_install#54]
破娃酱弃坑SSR后终于有人正式接盘了，建议把所有涉及SSR的部分直接替换为SSRR的。
https://github.com/shadowsocksrr

**Comment by msn1983aa** [comment]
我自己建的服务器端已是SSRR了

2018-01-27 19:34 GMT+08:00 Mr.Jos <notifications@github.com>:
