### ISSUE TITLE
Tried to install with shadowsocks_install

### ISSUE THREAD

**Issue by xiaopigu** [teddysun/shadowsocks_install#55]
Tried to use shadowsocks install and got this error.

Press any key to start...or Press Ctrl+C to cancel
Ign:1 http://archive.ubuntu.com/ubuntu zesty InRelease
Ign:2 http://security.ubuntu.com/ubuntu zesty-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu zesty-updates InRelease
Err:4 http://security.ubuntu.com/ubuntu zesty-security Release
  404  Not Found [IP: 91.189.88.162 80]
Ign:5 http://archive.ubuntu.com/ubuntu zesty-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu zesty Release
  404  Not Found [IP: 91.189.88.162 80]
Err:7 http://archive.ubuntu.com/ubuntu zesty-updates Release
  404  Not Found [IP: 91.189.88.162 80]
Err:8 http://archive.ubuntu.com/ubuntu zesty-backports Release
  404  Not Found [IP: 91.189.88.162 80]
Reading package lists...
E: The repository 'http://security.ubuntu.com/ubuntu zesty-security Release' does no longer have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu zesty Release' does no longer have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu zesty-updates Release' does no longer have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu zesty-backports Release' does no longer have a Release file.
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  grub-common libfreetype6
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libcroco3 libgomp1
Suggested packages:
  gettext-doc autopoint libasprintf-dev libgettextpo-dev
The following NEW packages will be installed:
  gettext libcroco3 libgomp1
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 1238 kB of archives.
After this operation, 4827 kB of additional disk space will be used.
Err:1 http://archive.ubuntu.com/ubuntu zesty/main amd64 libcroco3 amd64 0.6.11-2
  404  Not Found [IP: 91.189.88.162 80]
Err:2 http://archive.ubuntu.com/ubuntu zesty/main amd64 libgomp1 amd64 6.3.0-12ubuntu2
  404  Not Found [IP: 91.189.88.162 80]
Err:3 http://archive.ubuntu.com/ubuntu zesty/main amd64 gettext amd64 0.19.8.1-1ubuntu2
  404  Not Found [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libc/libcroco/libcroco3_0.6.11-2_amd64.deb  404  Not Found [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/gcc-6/libgomp1_6.3.0-12ubuntu2_amd64.deb  404  Not Found [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/gettext/gettext_0.19.8.1-1ubuntu2_amd64.deb  404  Not Found [IP: 91.189.88.162 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[Error] Failed to install gettext
Please visit: https://teddysun.com/486.html and contact.

**Comment by tmteamz** [comment]
did you have internet connection?

**Comment by xiaopigu** [comment]
Yes
