### ISSUE TITLE
Why IP is banned

### ISSUE THREAD

**Issue by yakiler** [teddysun/shadowsocks_install#63]
Hello，I tried to build a ssr service and succeed.I tried to build a ssr service and succeed,But after a few days I found it could not work, then I tried to use ping.pe, the network in China could not be connected.I'm sure I use ssr for encrypted transmission.It should be blocked by gwf and joined the blacklist.Can you give me some advice? How can this situation be improved?

**Comment by Dr-Bluemond** [comment]
Yes, ss and ssr is being monitored by gfw so I recommend you to use brook/lightsocks instead, you can get help at https://doub.ws

**Comment by yakiler** [comment]
thankyou
