### ISSUE TITLE
About "fast_open":false

### ISSUE THREAD

**Issue by 1v9** [teddysun/shadowsocks_install#74]
I used shadowsocks-libev-debian.sh to intall ss-libev.

My system is debian stretch and kernel is 4.16.0-0.bpo.2-amd64.

I found some code in the script like this, seems no problem.

``` bash
...
if version_gt ${kernel_version} 3.7.0; then
        return 0
...
if check_kernel_version && check_kernel_headers; then
        fast_open="true"
    else
        fast_open="false"
    fi
...
"fast_open":${fast_open},
```

But when I check config after installed ss-libev, fast_open is false.

```
 "fast_open":false,
```

Not a big problem just makes me  a little confused.

**Comment by teddysun** [comment]
kernel headers is necessary.
so function `check_kernel_headers` just check it.
