### ISSUE TITLE
请问是否可以出docker镜像？

### ISSUE THREAD

**Issue by JunHong1995** [teddysun/shadowsocks_install#76]
作者你好：
        请问下，是否可以出一个ssr+bbr增强版 的docker镜像，这样部署起来就更加的方便了~

**Comment by teddysun** [comment]
Docker 容器里开启 bbr 是没有意义的，因为 Docker 是在宿主机上工作的。
因此需要在宿主机上开启 bbr 才有意义。

**Comment by JunHong1995** [comment]
好的，学习了~
