### ISSUE TITLE
Cannot change password?

### ISSUE THREAD

**Issue by iPermanent** [teddysun/shadowsocks_install#77]
I used this script https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-libev-debian.sh
However, when I use the default password and port, it's OK, but not work when I customize the password and port number, My system is Debian 9

**Comment by huiyifyj** [comment]
Try run `/etc/init.d/shadowsocks restart` after update your password and port in configuration file.

**Comment by pursiyanov** [comment]
Hello guys, I have the same problem, I used script https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocksR.sh
When I customize multiuser,and restart service, it's not work, work only default port and password which i installed in first setup.
