### ISSUE TITLE
add "--no-check-certificate" for shadowsocks-libev-debian.sh

### ISSUE THREAD

**Issue by colingpt** [teddysun/shadowsocks_install#8]
don't know why i can't creat a pull request.

I found this line didn't work on Ubuntu 14.04 minimal due to lack of certificates, could be solved by change:

`ver=$(wget -qO- https://api.github.com/repos/shadowsocks/shadowsocks-libev/releases/latest | grep 'tag_name' | cut -d\" -f4)`

to

`ver=$(wget -qO- https://api.github.com/repos/shadowsocks/shadowsocks-libev/releases/latest --no-check-certificate | grep 'tag_name' | cut -d\" -f4)`

**Comment by teddysun** [comment]
Thank you. 
all done.

**Comment by colingpt** [comment]
I still can't create pull request...

just wired...

Is this because you did something specific, so I can't pull, or is this problem on my end?

I even can't pull back to my fork to update your changes.

**Comment by teddysun** [comment]
This project default allowed pull requests.
Refer URL:
https://help.github.com/articles/about-pull-requests/
